name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true

      - name: Lint (ruff)
        run: |
          ruff --version || pip install ruff
          ruff check .

      - name: Format check (black)
        run: |
          black --version || pip install black
          black --check .

      - name: Type check (mypy)
        run: |
          mypy --version || pip install mypy
          mypy eval || true

      - name: Unit tests
        run: |
          pip install pytest || true
          pytest -q || true
